name: Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        # https://github.com/actions/checkout/releases/tag/v3.4.0
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        # https://github.com/cycjimmy/semantic-release-action/commits/v4.0.0
        uses: cycjimmy/semantic-release-action@61680d0e9b02ff86f5648ade99e01be17f0260a4
        with:
          # https://github.com/semantic-release/release-notes-generator/commits/v12.0.0
          # https://github.com/semantic-release/git/commits/v10.0.1
          extra_plugins: |
            @semantic-release/release-notes-generator@v12.0.0
            @semantic-release/git@v10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
